version: "3.9"
services:
  gatsby-nginx:
    build:
      context: ./nginx-tor/
      dockerfile: Dockerfile
      args:
        - GATSBY_REPO
        - REPO_DIR
    container_name: ${DCNAME}-nginx
    hostname: gatsby-nginx
    ports:
      - ${NGINX_PORT}:80

  gatsby-tor:
    image: goldy/tor-hidden-service:0.4.4.6
    container_name: ${DCNAME}-tor
    links:
      - gatsby-nginx
    environment:
      SERVICE1_TOR_SERVICE_HOSTS: '80:gatsby-nginx:80'
      SERVICE1_TOR_SERVICE_VERSION: '3'
    volumes:
      - ../tor-keys:/var/lib/tor/hidden_service/

  gatsby-ipfs:
    build:
      context: ./ipfs/
      dockerfile: Dockerfile
      args:
        - GATSBY_REPO
        - REPO_DIR
        - IPFS_PORT
        - WIF
    container_name: ${DCNAME}-ipfs
    ports:
      # host:container
      - ${IPFS_PORT}:${IPFS_PORT}
    volumes:
      - ./config:/root/config
